[package]
name = "rust-musicplayer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

termsize="0.1.6"
termion="2.0.1"
rand="0.8"
rodio="0.17"
